# -*- coding: utf-8 -*-
"""Lab06SC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QnRZ9OdibZZSPG-7fM-iUL-8zkhVK7B-
"""

class Song:
  def __init__(self,title,artist,duration,year,album):
    self.title = title
    self.artist = artist
    self.duration = duration
    self.year = year
    self.album = album
  def get_simplified_view(self):
    return {
        "Title":self.title,
        "Artist":self.artist,
        "Duration":self.duration,
    }
song1 = Song("Venom","BP","3:34",2018,"1st")
song2 = Song("Dynamite","BTS","3:34",2020,"2nd")
print(song1.get_simplified_view())
print(song2.get_simplified_view())

class Vehicle:
  def __init__(self,make,model,year,color,mileage):
    self.make = make
    self.model = model
    self.year = year
    self.color = color
    self.mileage = mileage
  def simplified_view(self):
    return {
        "Make":self.make,
        "Model":self.model,
        "Year":self.year
    }
vehicle1 = Vehicle("Toyota", "Corolla", 2019, "Silver", 45000)
vehicle2 = Vehicle("Ford", "Mustang", 2022, "Red", 15000)
print(vehicle1.simplified_view())
print(vehicle2.simplified_view())

class Product:
  def __init__(self,name,price,description,image,category):
    self.name = name
    self.price = price
    self.description = description
    self.image = image
    self.category = category
  def simplified_view(self):
    return {
        "Name":self.name,
        "Price":self.price,
        "Image":self.image
    }
product1 = Product("Laptop", 999, "High-performance laptop", "laptop.jpg", "Electronics")
product2 = Product("T-shirt", 25, "Cotton t-shirt", "tshirt.jpg", "Clothing")
print(product1.simplified_view())
print(product2.simplified_view())



class Book:
  book_bank = []
  def add_book(self,book_id,title,author,num_copies):
    for book in self.book_bank:
      if book["Id"] == book_id:
        raise ValueError("ID Should Be Unique!!!")
        return
    if num_copies < 0:
        raise ValueError("Book Copies Cannot Be Negative")
        return
    self.book_bank.append({"Id":book_id,"Title":title,"Author":author,
                            "Number Of Copies":num_copies})
  def simplified_view(self):
    for i in self.book_bank:
      print(i)
book1 = Book();
book2 = Book();
book1.add_book(1, "Python Programming", "Guido van Rossum", 10)
book2.add_book(2, "The Great Gatsby", "F. Scott Fitzgerald", 5)
book1.simplified_view()

class Student:
  student_list = []
  def add_student(self,enroll_no,name,course):
    for student in self.student_list:
      if student["Enroll No"] == enroll_no:
        raise ValueError("Student Already Exists")
      if student["Name"] == name and student["Enroll No"] == enroll_no and student["course"] == course:
        raise ValueError("Course Already Registered")
    self.student_list.append({"Enroll No":enroll_no,"Name":name,"Course":course})
  def display_student(self):
    for i in self.student_list:
      print(i)
student1 = Student()
student1.add_student(27,"Kanwal","ES")
student2 = Student()
student2.add_student(22,"Mishal","CS")
student1.display_student()

